name: Test
on:
  pull_request:
  push: { branches: master }


jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ '2.7', '3.5', '3.7' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup pkg
        run: sudo apt-get update && sudo apt install libcurl4-openssl-dev libssl-dev
      - name: Setup python
        run: pip install -r maint/requirements.txt && pip install -r maint/requirements_dev.txt
      - name: Run tests
        run: python -m tortik_tests.runtests
  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: setup black
        run: pip install black
      - name: check
        run: black .